Web/Controllers/TemplateController.cs
using Data.Models;
using Microsoft.AspNet.Identity;
using Service;
using Shared.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Web.Controllers
{
    public class TemplateController : Controller
    {
        private IMenuServices _menuAppService;
        private IMenuInRolesServices _menuInRolesAppService;
        private IAccountServices _accountServices;
        private readonly UserManager userManager;
        private readonly RoleManager roleManager;
        public TemplateController(UserManager userManager, RoleManager roleManager, IMenuServices menuAppService, IMenuInRolesServices menuInRolesAppService,
            IAccountServices accountServices)
        {
            this.userManager = userManager;
            this.roleManager = roleManager;
            _menuInRolesAppService = menuInRolesAppService;
            _accountServices = accountServices;
            _menuAppService = menuAppService;
        }

        public PartialViewResult Header()
        {

            var lsCurrentRole = new List<string>();
            //Da login => lay list role
            if (User.Identity.IsAuthenticated)
            {
                var currentRole = CurrentRole();
                foreach (var name in currentRole)
                {
                    lsCurrentRole.Add(roleManager.FindByNameAsync(name).Result.Id);
                }
                string userId = User.Identity.GetUserId();
                var Name = userManager.Users.FirstOrDefault(c => c.Id == userId).Name;
                ViewBag.Name = Name;
            }
            //chua login/ thi lay role la anomymous
            else
            {
                lsCurrentRole.Add(roleManager.FindByNameAsync("Anonymous").Result.Id);
            }
            //get current menu tu role
            var lsCurrentMenu = _menuInRolesAppService.GetAll().Data.Where(c => lsCurrentRole.Contains(c.RoleId.ToString())).Select(c => c.MenuId);

            var model = _menuAppService.GetParent().Data
                .Where(c => lsCurrentMenu.Contains(c.Id))
                .OrderBy(c => c.Order)
                .Select(l => new MenuViewModel
                {
                    Id = l.Id,
                    Name = l.Name,
                    Url = l.Url,
                    Icon = l.Icon,
                    Order = l.Order,
                    IsActive = l.IsActive,
                    ParentId = l.ParentId,
                    Childrens = GetChildren(l.Id)
                });
            return PartialView(model);
        }
        public PartialViewResult Footer()
        {
            return PartialView();
        }

        private List<MenuViewModel> GetChildren(int parentId)
        {
            var lsCurrentRole = new List<string>();
            //Da login => lay list role
            if (User.Identity.IsAuthenticated)
            {
                var currentRole = CurrentRole();
                foreach (var name in currentRole)
                {
                    lsCurrentRole.Add(roleManager.FindByNameAsync(name).Result.Id);
                }
            }
            //chua login/ thi lay role la anomymous
            else
            {
                lsCurrentRole.Add(roleManager.FindByNameAsync("Anonymous").Result.Id);
            }
            //get current menu tu role
            var lsCurrentMenu = _menuInRolesAppService.GetAll().Data.Where(c => lsCurrentRole.Contains(c.RoleId.ToString())).Select(c => c.MenuId);

            return _menuAppService.GetChildren(parentId).Data
                 .Where(c => lsCurrentMenu.Contains(c.Id))
                 .OrderBy(l => l.Order)
                .Select(l => new MenuViewModel
                {
                    Id = l.Id,
                    Name = l.Name,
                    Url = l.Url,
                    Icon = l.Icon,
                    Order = l.Order,
                    IsActive = l.IsActive,
                    ParentId = l.ParentId,
                    Childrens = GetChildren(l.Id)
                }).ToList();
        }
        private List<string> CurrentRole()
        {
            var UserId = HttpContext.User.Identity.GetUserId();
            var currentRole = userManager.GetRoles(UserId);
            return currentRole.ToList();
        }


    }
}

Web/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- End Required meta tags -->
    <!-- Begin SEO tag -->
    <title>@ViewData["Title"] - Manage account</title>
    <meta property="og:title" content="Starter Template">
    <meta name="author" content="Beni Arisandi">
    <meta property="og:locale" content="en_US">
    <meta name="description" content="Responsive admin theme build on top of Bootstrap 4">
    <meta property="og:description" content="Responsive admin theme build on top of Bootstrap 4">
    <link rel="canonical" href="index.html">
    <meta property="og:url" content="index.html">
    <meta property="og:site_name" content="Looper - Bootstrap 4 Admin Theme">
    <!-- End SEO tag -->
    <!-- FAVICONS -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="~/Content/assets/apple-touch-icon.png">
    <link rel="shortcut icon" href="~/Content/assets/favicon.ico">
    <meta name="theme-color" content="#3063A0">
    <!-- End FAVICONS -->
    <script src="~/Content/assets/vendor/pace/pace.min.js"></script>
    <!-- BEGIN BASE STYLES -->
    <link rel="stylesheet" href="~/Content/assets/vendor/pace/pace.min.css">
    <link rel="stylesheet" href="~/Content/assets/vendor/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/Content/assets/vendor/open-iconic/css/open-iconic-bootstrap.min.css">
    <link rel="stylesheet" href="~/Content/assets/vendor/fontawesome/css/fontawesome.all.css">
    <link href="~/Content/assets/vendor/datatables/extensions/buttons/buttons.bootstrap4.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/Content/assets/vendor/toastr/toastr.min.css">
    <link rel="stylesheet" href="~/Content/assets/vendor/select2/css/select2.min.css">
    <!-- END BASE STYLES -->
    <!-- BEGIN THEME STYLES -->
    <link rel="stylesheet" href="~/Content/assets/stylesheets/main.min.css">
    <link rel="stylesheet" href="~/Content/assets/stylesheets/custom.css">
    <!-- END THEME STYLES -->
</head>
<body ng-app="MyApp">
    <!-- .app -->
    <div class="app">
        <!-- .app-header -->
        @Html.Action("Header", "Template")
        <!-- /.app-header -->
        <!-- .app-aside -->
        @Html.Action("Sidebar", "Template")
        <!-- /.app-aside -->
        <!-- .app-main -->
        <main class="app-main">
            <!-- .wrapper -->
            <div class="wrapper">
                <!-- .page -->
                <div class="page">
                    <!-- .page-inner -->
                    <div class="page-inner">
                        <!-- .page-title-bar -->
                        <header class="page-title-bar">
                            @*<h1 class="page-title"> Basic Elements </h1>*@
                            <!-- page title stuff goes here -->
                        </header>
                        <!-- /.page-title-bar -->
                        <!-- .page-section -->
                        <div class="page-section">
                            @RenderBody()
                            @Html.Partial("_Modal", new BootstrapModel { ID = "modal-action", AreaLabeledId = "modal-action", Size = ModalSize.Large })

                            <!-- page content goes here -->
                        </div>
                        <!-- /.page-section -->
                    </div>
                    <!-- /.page-inner -->
                </div>
                <!-- /.page -->
            </div>
            <!-- /.wrapper -->
        </main>
        <!-- /.app-main -->
    </div>
    <!-- Alert Danger Modal -->
    <div class="modal modal-alert fade" id="ExpiredModal" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="ExpiredLabel" aria-hidden="true">
        <!-- .modal-dialog -->
        <div class="modal-dialog" role="document">
            <!-- .modal-content -->
            <div class="modal-content">
                <!-- .modal-header -->
                <div class="modal-header">
                    <h5 class="modal-title">
                        <i class="fa fa-exclamation-triangle text-red mr-1"></i> Phiên làm viêc đã hết hạn
                    </h5>
                </div>
                <!-- /.modal-header -->
                <!-- .modal-body -->
                <div class="modal-body">
                    <p> Phiên làm việc của bạn đã hết hạn, vui lòng đăng nhập lại! </p>
                </div>
                <!-- /.modal-body -->
                <!-- .modal-footer -->
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger">Đăng nhập lại</button>
                </div>
                <!-- /.modal-footer -->
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
    <!-- /.modal -->
    <!-- /.app -->
    <!-- BEGIN BASE JS -->
    <script src="~/Content/assets/vendor/jquery/jquery.min.js"></script>
    <script src="~/Content/assets/vendor/bootstrap/js/popper.min.js"></script>
    <script src="~/Content/assets/vendor/bootstrap/js/bootstrap.min.js"></script>
    <!-- END BASE JS -->
    <!-- BEGIN PLUGINS JS -->
    <script src="~/Content/assets/vendor/stacked-menu/stacked-menu.min.js"></script>
    <script src="~/Content/assets/vendor/perfect-scrollbar/perfect-scrollbar.min.js"></script>
    <script src="~/Content/assets/vendor/datatables/jquery.dataTables.min.js"></script>
    <script src="~/Content/assets/vendor/datatables/dataTables.bootstrap4.min.js.js"></script>
    <script src="~/Content/assets/vendor/toastr/toastr.min.js"></script>
    <script src="~/Content/assets/javascript/pages/bootbox.min.js"></script>
    <script src="~/Content/assets/vendor/select2/js/select2.min.js"></script>
    <!-- END PLUGINS JS -->
    <!-- BEGIN THEME JS -->
    <script src="~/Content/assets/javascript/main.min.js"></script>
    <script src="~/Content/assets/javascript/site.js"></script>
    <script src="~/Content/assets/vendor/lodash/core.js"></script>
    <script src="~/Content/assets/angular-1.6.3/angular.min.js"></script>
    <script src="~/Content/assets/javascript/ApiHelper.js"></script>
    <script src="~/Content/assets/javascript/CommonHelper.js"></script>
    <script src="~/Content/assets/javascript/UtilFactory.js"></script>
    <script src="~/Content/assets/javascript/DataFactory.js"></script>
    @if (User.Identity.IsAuthenticated)
    {
        <script>
            var urlApi = "http://localhost:51581/api/";
        </script>
    }
    <script>
        (function ($) {
            function InitModal() {
                var $this = this;

                function initilizeModel() {
                    $("#modal-action").on('shown.bs.modal', function (e) {

                    }).on('hidden.bs.modal', function (e) {
                        $(this).removeData('bs.modal');
                    });
                }
                $this.init = function () {
                    initilizeModel();
                }
            }
            $(function () {
                var self = new InitModal();
                self.init();
            })
            //form to JSON
            $.fn.serializeFormJSON = function () {
                var o = {};
                var a = this.serializeArray();
                $.each(a, function () {
                    if (o[this.name]) {
                        if (!o[this.name].push) {
                            o[this.name] = [o[this.name]];
                        }
                        o[this.name].push(this.value || '');
                    } else {
                        o[this.name] = this.value || '';
                    }
                });
                return o;
            };

        }(jQuery))
    </script>
    <!--ANGULAR-->
    <script>
        var addController = function (name, controller) {
            try {
                MyApp.controller(name, controller);
            } catch (e) {
                console.log(JSON.stringify(e));
            }
        }
        var addFactory = function (name, factory) {
            try {
                MyApp.factory(name, factory);
            } catch (e) {
                console.log(JSON.stringify(e));
            }
        }
        //var lstDependency = [];
        //lstDependency.push("ngRoute");
        //lstDependency.push("angular.filter");
        var MyApp = angular.module("MyApp", []);

        addFactory("$localstorage", $localstorage);
        addFactory("ApiHelper", ApiHelper);
        addFactory("CommonHelper", CommonHelper);
        addFactory("UtilFactory", UtilFactory);
        addFactory("DataFactory", DataFactory);
    </script>

    @RenderSection("scripts", required: false)
</body>
</html>

Web/Areas/Admin/Views/Shared/_LayoutFlare.cshtml
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- End Required meta tags -->
    <!-- Begin SEO tag -->
    <title>@ViewData["Title"] - Manage account</title>
    <meta property="og:title" content="Starter Template">
    <meta name="author" content="Beni Arisandi">
    <meta property="og:locale" content="en_US">
    <meta name="description" content="Responsive admin theme build on top of Bootstrap 4">
    <meta property="og:description" content="Responsive admin theme build on top of Bootstrap 4">
    <link rel="canonical" href="index.html">
    <meta property="og:url" content="index.html">
    <meta property="og:site_name" content="Looper - Bootstrap 4 Admin Theme">
    <!-- End SEO tag -->
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Flare Premium Bootstrap Admin Dashboard Template</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="~/Content/assets/flare/vendors/iconfonts/simple-line-icon/css/simple-line-icons.css">
    <link rel="stylesheet" href="~/Content/assets/flare/vendors/css/vendor.bundle.base.css">
    <link rel="stylesheet" href="~/Content/assets/flare/vendors/css/vendor.bundle.addons.css">
    <link rel="stylesheet" href="~/Content/assets/flare/vendors/iconfonts/font-awesome/css/font-awesome.min.css" />
    <!-- endinject -->
    <!-- plugin css for this page -->
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link href="~/Content/assets/flare/css/style.css" rel="stylesheet" />
    <!-- endinject -->
</head>
<body ng-app="MyApp">
    <!-- .app -->
    @Html.Action("Header", "Template", new { Area = "" })
    <div ng-controller="MasterPageController" ng-cloak>
        <div id="cover-spin" ng-show="MasterPage.IsLoading"></div>
    </div>s
    <!-- partial -->
    <div class="container-fluid page-body-wrapper">
        <div class="main-panel">
            @RenderBody()
            @*<div class="content-wrapper">
        </div>*@
            <!-- content-wrapper ends -->
            <!-- partial:../../partials/_footer.html -->
            @Html.Action("Footer", "Template", new { Area = "" })
            <!-- partial -->
        </div>
        <!-- main-panel ends -->
    </div>
    <!-- page-body-wrapper ends -->
    <!-- Alert Danger Modal -->
    <div class="modal modal-alert fade" id="ExpiredModal" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="ExpiredLabel" aria-hidden="true">
        <!-- .modal-dialog -->
        <div class="modal-dialog" role="document">
            <!-- .modal-content -->
            <div class="modal-content">
                <!-- .modal-header -->
                <div class="modal-header">
                    <h5 class="modal-title">
                        <i class="fa fa-exclamation-triangle text-red mr-1"></i> Phiên làm viêc đã hết hạn
                    </h5>
                </div>
                <!-- /.modal-header -->
                <!-- .modal-body -->
                <div class="modal-body">
                    <p> Phiên làm việc của bạn đã hết hạn, vui lòng đăng nhập lại! </p>
                </div>
                <!-- /.modal-body -->
                <!-- .modal-footer -->
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger">Đăng nhập lại</button>
                </div>
                <!-- /.modal-footer -->
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
    <!-- /.modal -->
    <!-- /.app -->
    <script src="~/Content/assets/flare/vendors/js/vendor.bundle.base.js"></script>
    <script src="~/Content/assets/flare/vendors/js/vendor.bundle.addons.js"></script>
    <!-- endinject -->
    <!-- Plugin js for this page-->
    <!-- End plugin js for this page-->
    <!-- inject:js -->
    <script src="~/Content/assets/flare/js/template.js"></script>
    <!-- Custom js for this page-->
    <script src="~/Content/assets/flare/vendors/js/popover.js"></script>
    <script src="~/Content/assets/flare/vendors/js/tooltips.js"></script>
    <script src="~/Content/assets/flare/vendors/js/alerts.js"></script>
    <!-- endinject -->
    <!-- Custom js for this page-->
    <!-- End custom js for this page-->
    <script src="~/Content/assets/javascript/site.js"></script>
    <script src="~/Content/assets/vendor/lodash/core.js"></script>
    <script src="~/Content/assets/angular-1.6.3/angular.min.js"></script>
    <script src="~/Content/assets/angular-1.6.3/angular-route.min.js"></script>
    <script src="~/Content/assets/app/app-bundle.js"></script>
    <!--ANGULAR-->
    @RenderSection("scripts", required: false)
</body>
</html>